BN:
  ALPHA: 0.1
OPTIM:
  METHOD: 'Adam'
  STEPS: 1
  LR: 1e-3
  BETA: 0.9
  MOMENTUM: 0.9
  DAMPENING: 0.0
  NESTEROV: true
  WD: 0.0
TEACHER:
  MOMENTUM: 0.999
CONTRAST:
  TEMPERATURE: 0.1
  PROJECTION_DIM: 128
  MODE: 'all'
DETERMINISM: true
RNG_SEED: 2020