name: unida_tta_env_clip
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.9.1=hac33072_0
  - blosc=1.21.6=he440d0b_1
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py310hf71b8c6_2
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h4bc722e_7
  - c-blosc2=2.15.2=h3122c55_1
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - charls=2.4.2=h59595ed_0
  - dav1d=1.2.1=hd590300_0
  - freetype=2.13.3=ha770c72_1
  - giflib=5.2.2=hd590300_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - imagecodecs=2024.12.30=py310h78a9a29_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - jxrlib=1.1=hd590300_3
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.3=h59595ed_0
  - libavif16=1.2.1=hbb36593_2
  - libblas=3.9.0=20_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=20_linux64_openblas
  - libdeflate=1.23=h86f0d12_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - libhwy=1.2.0=hf40a0c7_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libjxl=0.11.1=h7b0646d_1
  - liblapack=3.9.0=20_linux64_openblas
  - liblzma=5.8.1=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libpng=1.6.47=h943b412_0
  - libsqlite=3.49.1=hee588c1_2
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.7.0=hd9ff511_4
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - lz4-c=1.10.0=h5888daf_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.4.2=pyh267e887_2
  - numpy=1.24.3=py310ha4c1d20_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.0=h7b32b05_1
  - pillow=11.1.0=py310h7e6dc6c_0
  - pip=25.0.1=pyh8b19718_0
  - platformdirs=4.3.7=pyh29332c3_0
  - pooch=1.8.2=pyhd8ed1ab_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.16=habfa6aa_2_cpython
  - python_abi=3.10=6_cp310
  - pywavelets=1.8.0=py310hf462985_0
  - rav1e=0.6.6=he8a937b_2
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=pyhd8ed1ab_1
  - scikit-image=0.25.0=py310h5eaa309_0
  - scipy=1.10.1=py310ha4c1d20_3
  - setuptools=78.1.0=pyhff2d567_0
  - snappy=1.2.1=h8bd8927_1
  - svt-av1=3.0.2=h5888daf_0
  - tifffile=2025.3.30=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - zfp=1.0.1=h5888daf_2
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib-ng=2.2.4=h7955e40_0
  - zstandard=0.23.0=py310ha75aee5_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - backoff==2.2.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - datasets==3.5.0
      - diskcache==5.6.3
      - docker-pycreds==0.4.0
      - emoji==2.14.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - filelock==3.18.0
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gql==3.5.2
      - graphql-core==3.2.4
      - huggingface-hub==0.30.2
      - iopath==0.1.10
      - joblib==1.5.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - multidict==6.3.2
      - omegaconf==2.3.0
      - openai-clip==1.0.1
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - opentelemetry-proto==1.31.1
      - packaging==24.2
      - pandas==2.2.3
      - portalocker==3.1.1
      - propcache==0.3.1
      - protobuf==5.29.4
      - psutil==7.0.0
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pygments==2.19.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests-toolbelt==1.0.0
      - rich==14.0.0
      - rpds-py==0.24.0
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - sentry-sdk==2.25.1
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - submitit==1.5.2
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      # - torch==1.13.1+cu117
      # - torchaudio==0.13.1+cu117
      # - torchvision==0.14.1+cu117
      - tqdm==4.67.1
      - transformers==4.52.4
      - typing-extensions==4.13.1
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.3.0
      - uuid-utils==0.10.0
      - wand==0.6.13
      - wandb==0.19.9
      - wcwidth==0.2.13
      - weave==0.51.42
      - yacs==0.1.8
      - yarl==1.19.0
# prefix: /scratch/sgw3fy/envs/unida_tta_envs/unida_tta_env_clip
